import { StringColumn, Table } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder from the user's data-model elicitation.
// Source: src/lib/assistantBehavior.ts#parseTableDefs.
export const x_1939459_iplegal_https = Table({
    name: 'x_1939459_iplegal_https',
    label: "Https",
    schema: {
        www_figma_com_make_uksn7hqnzimvkydc7zoyv6_web_design_system_for_ip_legal_t_5yv1cy4d1ajkrsxe_1: StringColumn({ label: "Www Figma Com Make Uksn7hqnzimvkydc7zoyv6 Web Design System For Ip Legal T 5yv1cy4d1ajkrsxe 1" }),
    },
})
