import { ChoiceColumn, DateColumn, DecimalColumn, IntegerColumn, ReferenceColumn, StringColumn, Table } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder from the user's data-model elicitation.
// Source: src/lib/assistantBehavior.ts#parseTableDefs.
export const x_1939459_property_work_log = Table({
    name: 'x_1939459_property_work_log',
    label: "Work Log",
    schema: {
        work_order: ReferenceColumn({ label: "work_order", mandatory: true, referenceTable: 'x_1939459_property_work_order' }),
        entry_type: ChoiceColumn({ label: "entry_type", mandatory: true, choices: {} }),
        minutes_worked: IntegerColumn({ label: "minutes_worked" }),
        cost: DecimalColumn({ label: "cost" }),
        date_worked: DateColumn({ label: "date_worked" }),
        notes: StringColumn({ label: "notes", maxLength: 4000 }),
    },
})
