import { DecimalColumn, ReferenceColumn, Table } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder from the user's data-model elicitation.
// Source: src/lib/assistantBehavior.ts#parseTableDefs.
export const x_1939459_property_work_order = Table({
    name: 'x_1939459_property_work_order',
    label: "Work Order",
    schema: {
        property: ReferenceColumn({ label: "property", mandatory: true, referenceTable: 'x_1939459_property_property' }),
        space: ReferenceColumn({ label: "space", mandatory: true, referenceTable: 'x_1939459_property_space' }),
        category: ReferenceColumn({ label: "category", mandatory: true, referenceTable: 'x_1939459_property_repair_category' }),
        estimated_cost: DecimalColumn({ label: "estimated_cost" }),
    },
})
