import { BooleanColumn, ChoiceColumn, ReferenceColumn, StringColumn, Table } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder from the user's data-model elicitation.
// Source: src/lib/assistantBehavior.ts#parseTableDefs.
export const x_1939459_property_space = Table({
    name: 'x_1939459_property_space',
    label: "Space",
    schema: {
        property: ReferenceColumn({ label: "property", mandatory: true, referenceTable: 'x_1939459_property_property' }),
        space_id: StringColumn({ label: "space_id", mandatory: true }),
        floor: StringColumn({ label: "floor" }),
        type: ChoiceColumn({ label: "type", choices: {} }),
        active: BooleanColumn({ label: "active" }),
    },
})
