import { BooleanColumn, StringColumn, Table } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder from the user's data-model elicitation.
// Source: src/lib/assistantBehavior.ts#parseTableDefs.
export const x_1939459_property_property = Table({
    name: 'x_1939459_property_property',
    label: "Property",
    schema: {
        name: StringColumn({ label: "name", mandatory: true }),
        code: StringColumn({ label: "code" }),
        address1: StringColumn({ label: "address1" }),
        address2: StringColumn({ label: "address2" }),
        city: StringColumn({ label: "city" }),
        state: StringColumn({ label: "state" }),
        postal_code: StringColumn({ label: "postal_code" }),
        active: BooleanColumn({ label: "active" }),
    },
})
