function ($scope) {
    var c = this;
    try { c.typeStyles = {success:'bg-[var(--iplegal-success)] border-[var(--iplegal-success)]',warning:'bg-[var(--iplegal-warning)] border-[var(--iplegal-warning)]',danger:'bg-[var(--iplegal-danger)] border-[var(--iplegal-danger)]',info:'bg-[var(--iplegal-info)] border-[var(--iplegal-info)]'}; $scope.typeStyles = c.typeStyles; } catch (e) { c.typeStyles = null; $scope.typeStyles = null; }
    try { c.statusStyles = {'Open':'bg-[var(--iplegal-info-bg)] text-[var(--iplegal-info)] border-[var(--iplegal-info-border)]','In Review':'bg-[var(--iplegal-warning-bg)] text-[var(--iplegal-warning)] border-[var(--iplegal-warning-border)]','Approved':'bg-[var(--iplegal-success-bg)] text-[var(--iplegal-success)] border-[var(--iplegal-success-border)]','Rejected':'bg-[var(--iplegal-danger-bg)] text-[var(--iplegal-danger)] border-[var(--iplegal-danger-border)]','On Hold':'bg-[var(--iplegal-gray-100)] text-[var(--iplegal-gray-700)] border-[var(--iplegal-gray-300)]'}; $scope.statusStyles = c.statusStyles; } catch (e) { c.statusStyles = null; $scope.statusStyles = null; }
    try { c.riskStyles = {'Low':'bg-[var(--iplegal-success-bg)] text-[var(--iplegal-success)] border-[var(--iplegal-success-border)]','Med':'bg-[var(--iplegal-warning-bg)] text-[var(--iplegal-warning)] border-[var(--iplegal-warning-border)]','High':'bg-[#FED7AA] text-[#C2410C] border-[#FDBA74]','Critical':'bg-[var(--iplegal-danger-bg)] text-[var(--iplegal-danger)] border-[var(--iplegal-danger-border)]'}; $scope.riskStyles = c.riskStyles; } catch (e) { c.riskStyles = null; $scope.riskStyles = null; }
    try { c.featuredDecisions = [{topic:'Software Patent Eligibility under Alice Corp.',summary:'Recent guidance on abstract idea determination for AI/ML algorithms and technical improvements to computer functionality.',tags:['Patent','Software','AI/ML'],date:'Apr 15, 2026'},{topic:'Open Source License Compliance',summary:'Best practices for GPL, MIT, and Apache 2.0 compliance in commercial software products and derivative works.',tags:['Copyright','Open Source','Licensing'],date:'Apr 10, 2026'},{topic:'API Copyright Protection',summary:'Guidance on copyrightability of APIs following Oracle v. Google and implications for software interoperability.',tags:['Copyright','API','Fair Use'],date:'Apr 5, 2026'}]; $scope.featuredDecisions = c.featuredDecisions; } catch (e) { c.featuredDecisions = null; $scope.featuredDecisions = null; }
    try { c.priorityColors = {Low:'text-[var(--iplegal-gray-600)]',Medium:'text-[var(--iplegal-info)]',High:'text-[var(--iplegal-warning)]',Critical:'text-[var(--iplegal-danger)]'}; $scope.priorityColors = c.priorityColors; } catch (e) { c.priorityColors = null; $scope.priorityColors = null; }
    try { c.links = [{icon:'➕',label:'New request',description:'Start a new IP submission'},{icon:'📝',label:'Drafts',description:'Resume saved drafts'},{icon:'❓',label:'Help',description:'Get assistance and support'},{icon:'📄',label:'Policies',description:'IP policies and guidelines'}]; $scope.links = c.links; } catch (e) { c.links = null; $scope.links = null; }
    try { c.steps = ['Select Type','Intake Form','Review & Submit']; $scope.steps = c.steps; } catch (e) { c.steps = null; $scope.steps = null; }
    try { c.guidanceByType = {patent:{items:['Detailed description of the invention','Diagrams or flowcharts (if applicable)','List of all inventors','Prior art search results (if available)','Information about any public disclosures'],tips:['File before any public disclosure to preserve rights','Include technical details about how it works','Describe the problem it solves and advantages']},trademark:{items:['Clear representation of the mark (logo/wordmark)','Description of goods/services','Evidence of first use in commerce','Examples of mark usage in marketing'],tips:['Ensure the mark is distinctive and not generic','Search existing trademarks to avoid conflicts','Provide samples showing the mark in actual use']},copyright:{items:['Complete copy of the work','Date of creation and publication','List of all authors/creators','Information about derivative works'],tips:['Copyright exists from creation, but registration provides benefits','Include all versions if the work has been updated','Document chain of authorship for clarity']}}; $scope.guidanceByType = c.guidanceByType; } catch (e) { c.guidanceByType = null; $scope.guidanceByType = null; }
    try { c.requestTypes = [{id:'patent',name:'Patent Application',description:'Protect inventions, algorithms, and technical innovations. Grants exclusive rights to make, use, and sell the invention.',defaultPriority:'High',icon:'💡'},{id:'trademark',name:'Trademark Registration',description:'Protect brand names, logos, and slogans. Prevents others from using confusingly similar marks in commerce.',defaultPriority:'Medium',icon:'®'},{id:'copyright',name:'Copyright Protection',description:'Protect original works of authorship including software code, documentation, and creative content.',defaultPriority:'Medium',icon:'©'},{id:'license',name:'License Agreement Review',description:'Review and negotiate license agreements for software, open source, or intellectual property.',defaultPriority:'Low',icon:'📄'},{id:'opinion',name:'Freedom to Operate Opinion',description:'Assess whether a product or service may infringe on existing patents or IP rights.',defaultPriority:'High',icon:'🔍'},{id:'infringement',name:'Infringement Review',description:'Report potential infringement of company IP rights or respond to infringement claims.',defaultPriority:'Critical',icon:'⚠️'}]; $scope.requestTypes = c.requestTypes; } catch (e) { c.requestTypes = null; $scope.requestTypes = null; }
    try { c.mockRequests = [{number:'REQ-2345',title:'ML Model Patent Application',type:'Patent',status:'In Review',dueDate:'2026-05-10',priority:'High',risk:'High',lastUpdated:'2026-04-28'},{number:'REQ-2340',title:'API Framework Copyright',type:'Copyright',status:'Open',dueDate:'2026-05-15',priority:'Medium',risk:'Low',lastUpdated:'2026-04-27'},{number:'REQ-2338',title:'Product Name Trademark',type:'Trademark',status:'In Review',dueDate:'2026-05-05',priority:'Critical',risk:'Med',lastUpdated:'2026-04-29'},{number:'REQ-2335',title:'Open Source License Review',type:'License',status:'Approved',dueDate:'2026-04-30',priority:'Low',risk:'Low',lastUpdated:'2026-04-26'},{number:'REQ-2330',title:'Cloud Architecture Patent',type:'Patent',status:'On Hold',dueDate:'2026-05-20',priority:'Medium',risk:'Med',lastUpdated:'2026-04-25'},{number:'REQ-2328',title:'Logo Trademark Registration',type:'Trademark',status:'Rejected',dueDate:'2026-04-28',priority:'High',risk:'Critical',lastUpdated:'2026-04-24'},{number:'REQ-2325',title:'Software Copyright Protection',type:'Copyright',status:'Approved',dueDate:'2026-05-01',priority:'Medium',risk:'Low',lastUpdated:'2026-04-23'},{number:'REQ-2320',title:'Freedom to Operate Analysis',type:'FTO',status:'In Review',dueDate:'2026-05-12',priority:'High',risk:'High',lastUpdated:'2026-04-28'},{number:'REQ-2315',title:'Competitor Infringement Review',type:'Infringement',status:'Open',dueDate:'2026-05-08',priority:'Critical',risk:'Critical',lastUpdated:'2026-04-29'},{number:'REQ-2310',title:'UI Design Patent Application',type:'Patent',status:'In Review',dueDate:'2026-05-18',priority:'Medium',risk:'Med',lastUpdated:'2026-04-27'}]; $scope.mockRequests = c.mockRequests; } catch (e) { c.mockRequests = null; $scope.mockRequests = null; }
    try { c.mockRequest = {number:'REQ-2345',title:'ML Model Patent Application',status:'In Review',priority:'High',risk:'High',type:'Patent Application',submittedBy:'Jane Doe',department:'Engineering',businessUnit:'AI Research',description:'Patent application for a novel machine learning algorithm that improves natural language processing accuracy by 15% while reducing computational requirements by 30%. The innovation uses a hybrid attention mechanism combined with dynamic pruning.',submittedDate:'2026-04-15',dueDate:'2026-05-10',reviewDueDate:'2026-05-01'}; $scope.mockRequest = c.mockRequest; } catch (e) { c.mockRequest = null; $scope.mockRequest = null; }
    try { c.mockIntakeResponses = [{question:'Type of Invention',answer:'Software/Algorithm'},{question:'Inventor Name(s)',answer:'Jane Doe, Robert Smith, Emily Chen'},{question:'Prior Art Search Conducted',answer:'Yes'},{question:'Has this been publicly disclosed?',answer:'No'},{question:'Detailed Description',answer:'The ML model uses a novel hybrid attention mechanism that combines local and global context...'}]; $scope.mockIntakeResponses = c.mockIntakeResponses; } catch (e) { c.mockIntakeResponses = null; $scope.mockIntakeResponses = null; }
    try { c.mockWorkflow = [{name:'Submitted',status:'completed',completedDate:'2026-04-15'},{name:'Initial Review',status:'completed',completedDate:'2026-04-18'},{name:'Legal Analysis',status:'current'},{name:'Approval',status:'pending',isParallel:true},{name:'Filing',status:'pending'}]; $scope.mockWorkflow = c.mockWorkflow; } catch (e) { c.mockWorkflow = null; $scope.mockWorkflow = null; }
    try { c.mockReviewTasks = [{id:'1',task:'Prior Art Search Review',assignee:'Sarah Johnson',dueDate:'2026-04-25',status:'Completed',decision:'Approved - No conflicts found'},{id:'2',task:'Technical Evaluation',assignee:'Michael Brown',dueDate:'2026-04-28',status:'In Progress'},{id:'3',task:'Patent Attorney Review',assignee:'David Lee',dueDate:'2026-05-01',status:'Pending'}]; $scope.mockReviewTasks = c.mockReviewTasks; } catch (e) { c.mockReviewTasks = null; $scope.mockReviewTasks = null; }
    try { c.mockApprovals = [{approver:'Tom Wilson',role:'Engineering Manager',outcome:'Approved',timestamp:'2026-04-16 10:30 AM',comments:'Strong technical innovation with clear commercial value.'},{approver:'Lisa Anderson',role:'IP Director',outcome:'Approved',timestamp:'2026-04-17 02:15 PM',comments:'Meets patentability criteria. Recommend proceeding with filing.'},{approver:'James Martinez',role:'Legal Counsel',outcome:'Pending',timestamp:undefined}]; $scope.mockApprovals = c.mockApprovals; } catch (e) { c.mockApprovals = null; $scope.mockApprovals = null; }
    try { c.mockDocuments = [{name:'Technical Specification.pdf',category:'Technical Documentation',uploadedBy:'Jane Doe',uploadedDate:'2026-04-15',size:'2.4 MB'},{name:'Algorithm Flowchart.png',category:'Diagrams',uploadedBy:'Jane Doe',uploadedDate:'2026-04-15',size:'856 KB'},{name:'Prior Art Analysis.pdf',category:'Legal Analysis',uploadedBy:'Sarah Johnson',uploadedDate:'2026-04-20',size:'1.8 MB'}]; $scope.mockDocuments = c.mockDocuments; } catch (e) { c.mockDocuments = null; $scope.mockDocuments = null; }
    try { c.mockActivity = [{user:'System',action:'Request status changed to "In Review"',timestamp:'2026-04-18 09:00 AM'},{user:'Sarah Johnson',action:'Completed prior art search review',timestamp:'2026-04-25 03:45 PM',comment:'No conflicting patents found in initial search.'},{user:'Michael Brown',action:'Started technical evaluation',timestamp:'2026-04-26 10:15 AM'},{user:'Jane Doe',action:'Uploaded additional documentation',timestamp:'2026-04-27 11:30 AM'}]; $scope.mockActivity = c.mockActivity; } catch (e) { c.mockActivity = null; $scope.mockActivity = null; }
    try { c.allTags = ['Patent','Trademark','Copyright','Open Source','Licensing','AI/ML','Software','API','Fair Use','Compliance']; $scope.allTags = c.allTags; } catch (e) { c.allTags = null; $scope.allTags = null; }
    try { c.documentCategories = ['Technical Documentation','Legal Analysis','Prior Art','Diagrams','Supporting Materials','Correspondence','Contracts','Other']; $scope.documentCategories = c.documentCategories; } catch (e) { c.documentCategories = null; $scope.documentCategories = null; }
    try { c.showEmptyState = false; $scope.showEmptyState = c.showEmptyState; } catch (e) { c.showEmptyState = null; $scope.showEmptyState = null; }
    try { c.showWizard = false; $scope.showWizard = c.showWizard; } catch (e) { c.showWizard = null; $scope.showWizard = null; }
    try { c.showMyRequests = false; $scope.showMyRequests = c.showMyRequests; } catch (e) { c.showMyRequests = null; $scope.showMyRequests = null; }
    try { c.showRequestDetail = false; $scope.showRequestDetail = c.showRequestDetail; } catch (e) { c.showRequestDetail = null; $scope.showRequestDetail = null; }
    try { c.showLegalDecisions = false; $scope.showLegalDecisions = c.showLegalDecisions; } catch (e) { c.showLegalDecisions = null; $scope.showLegalDecisions = null; }
    try { c.prefillRelatedType = undefined; $scope.prefillRelatedType = c.prefillRelatedType; } catch (e) { c.prefillRelatedType = null; $scope.prefillRelatedType = null; }
    try { c.show = false; $scope.show = c.show; } catch (e) { c.show = null; $scope.show = null; }
    try { c.showUserMenu = false; $scope.showUserMenu = c.showUserMenu; } catch (e) { c.showUserMenu = null; $scope.showUserMenu = null; }
    try { c.currentStep = 0; $scope.currentStep = c.currentStep; } catch (e) { c.currentStep = null; $scope.currentStep = null; }
    try { c.selectedType = 'All'; $scope.selectedType = c.selectedType; } catch (e) { c.selectedType = null; $scope.selectedType = null; }
    try { c.formData = {
  name: '',
  category: '',
  url: '',
  notes: ''
}; $scope.formData = c.formData; } catch (e) { c.formData = null; $scope.formData = null; }
    try { c.errors = {}; $scope.errors = c.errors; } catch (e) { c.errors = null; $scope.errors = null; }
    try { c.attachments = []; $scope.attachments = c.attachments; } catch (e) { c.attachments = null; $scope.attachments = null; }
    try { c.confirmed = false; $scope.confirmed = c.confirmed; } catch (e) { c.confirmed = null; $scope.confirmed = null; }
    try { c.isDragging = false; $scope.isDragging = c.isDragging; } catch (e) { c.isDragging = null; $scope.isDragging = null; }
    try { c.searchQuery = ''; $scope.searchQuery = c.searchQuery; } catch (e) { c.searchQuery = null; $scope.searchQuery = null; }
    try { c.selectedStatuses = []; $scope.selectedStatuses = c.selectedStatuses; } catch (e) { c.selectedStatuses = null; $scope.selectedStatuses = null; }
    try { c.selectedPriority = 'All'; $scope.selectedPriority = c.selectedPriority; } catch (e) { c.selectedPriority = null; $scope.selectedPriority = null; }
    try { c.selectedRisk = 'All'; $scope.selectedRisk = c.selectedRisk; } catch (e) { c.selectedRisk = null; $scope.selectedRisk = null; }
    try { c.dateFrom = ''; $scope.dateFrom = c.dateFrom; } catch (e) { c.dateFrom = null; $scope.dateFrom = null; }
    try { c.dateTo = ''; $scope.dateTo = c.dateTo; } catch (e) { c.dateTo = null; $scope.dateTo = null; }
    try { c.currentPage = 1; $scope.currentPage = c.currentPage; } catch (e) { c.currentPage = null; $scope.currentPage = null; }
    try { c.showFilters = false; $scope.showFilters = c.showFilters; } catch (e) { c.showFilters = null; $scope.showFilters = null; }
    try { c.showTaskModal = false; $scope.showTaskModal = c.showTaskModal; } catch (e) { c.showTaskModal = null; $scope.showTaskModal = null; }
    try { c.selectedTask = null; $scope.selectedTask = c.selectedTask; } catch (e) { c.selectedTask = null; $scope.selectedTask = null; }
    try { c.newComment = ''; $scope.newComment = c.newComment; } catch (e) { c.newComment = null; $scope.newComment = null; }
    try { c.showAddDocumentModal = false; $scope.showAddDocumentModal = c.showAddDocumentModal; } catch (e) { c.showAddDocumentModal = null; $scope.showAddDocumentModal = null; }
    try { c.documents = mockDocuments; $scope.documents = c.documents; } catch (e) { c.documents = null; $scope.documents = null; }
    try { c.selectedTags = []; $scope.selectedTags = c.selectedTags; } catch (e) { c.selectedTags = null; $scope.selectedTags = null; }
    try { c.selectedOwner = 'All'; $scope.selectedOwner = c.selectedOwner; } catch (e) { c.selectedOwner = null; $scope.selectedOwner = null; }
    try { c.selectedVisibility = 'All'; $scope.selectedVisibility = c.selectedVisibility; } catch (e) { c.selectedVisibility = null; $scope.selectedVisibility = null; }
    try { c.sortBy = 'Recent'; $scope.sortBy = c.sortBy; } catch (e) { c.sortBy = null; $scope.sortBy = null; }
    try { c.selectedDecision = null; $scope.selectedDecision = c.selectedDecision; } catch (e) { c.selectedDecision = null; $scope.selectedDecision = null; }
    try { c.touched = {}; $scope.touched = c.touched; } catch (e) { c.touched = null; $scope.touched = null; }
    // Server-supplied data.* is already on $scope under the data namespace,
    // but expose every server data key on $scope as a bare name too so
    // templates that reference top-level literals via {{ literalName }}
    // resolve regardless of whether the seed above caught them. Last-write
    // wins — server data overrides the static initials when both are set.
    if (c.data && typeof c.data === 'object') {
        for (var k in c.data) {
            if (Object.prototype.hasOwnProperty.call(c.data, k)) {
                $scope[k] = c.data[k];
            }
        }
    }
}
