import { SPWidget } from '@servicenow/sdk/core'

// Generated by Vibe OverYonder M5 — Figma-derived widget. The HTML is the
// AngularJS template emitted by jsxToTemplate.ts; the SCSS is the Tailwind
// + user :root tokens compiled by tailwindCompile.ts and scoped to
// .vibe-figma-root so the Service Portal chrome isn't reset. The client
// script seeds the controller scope with every useState initial + literal
// binding so {{ }} expressions in the template resolve at first render
// (Service Portal isolates the widget scope, so an in-template ng-init
// can't reach the same scope the templates evaluate against).
SPWidget({
    $id: Now.ID['3fdd7a9f4cafa2c112b58f73f372f505'],
    name: "Legal IP Requests — Figma",
    id: 'iplegal-figma',
    htmlTemplate: Now.include('./figma-widget.html'),
    customCss: Now.include('./figma-widget.scss'),
    serverScript: Now.include('./figma-widget.server.js'),
    clientScript: Now.include('./figma-widget.client.js'),
    hasPreview: true,
})
